package dev.ngai.fantastic.data.source.local.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import dev.ngai.fantastic.data.UserPrivate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_PRIVATE".
*/
public class UserPrivateDao extends AbstractDao<UserPrivate, Long> {

    public static final String TABLENAME = "USER_PRIVATE";

    /**
     * Properties of entity UserPrivate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CollectIds = new Property(1, String.class, "collectIds", false, "COLLECT_IDS");
        public final static Property PayAlbumIds = new Property(2, String.class, "payAlbumIds", false, "PAY_ALBUM_IDS");
    }


    public UserPrivateDao(DaoConfig config) {
        super(config);
    }
    
    public UserPrivateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_PRIVATE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"COLLECT_IDS\" TEXT," + // 1: collectIds
                "\"PAY_ALBUM_IDS\" TEXT);"); // 2: payAlbumIds
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_PRIVATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserPrivate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String collectIds = entity.getCollectIds();
        if (collectIds != null) {
            stmt.bindString(2, collectIds);
        }
 
        String payAlbumIds = entity.getPayAlbumIds();
        if (payAlbumIds != null) {
            stmt.bindString(3, payAlbumIds);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserPrivate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String collectIds = entity.getCollectIds();
        if (collectIds != null) {
            stmt.bindString(2, collectIds);
        }
 
        String payAlbumIds = entity.getPayAlbumIds();
        if (payAlbumIds != null) {
            stmt.bindString(3, payAlbumIds);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserPrivate readEntity(Cursor cursor, int offset) {
        UserPrivate entity = new UserPrivate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // collectIds
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // payAlbumIds
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserPrivate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCollectIds(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPayAlbumIds(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserPrivate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserPrivate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserPrivate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
