package dev.weihl.amazing.data.source.local.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import dev.weihl.amazing.data.bean.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Void> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserId = new Property(0, String.class, "userId", false, "USER_ID");
        public final static Property UserEmail = new Property(1, String.class, "userEmail", false, "USER_EMAIL");
        public final static Property CollectAlbumIds = new Property(2, String.class, "collectAlbumIds", false, "COLLECT_ALBUM_IDS");
        public final static Property PayAlbumIds = new Property(3, String.class, "payAlbumIds", false, "PAY_ALBUM_IDS");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"USER_ID\" TEXT," + // 0: userId
                "\"USER_EMAIL\" TEXT," + // 1: userEmail
                "\"COLLECT_ALBUM_IDS\" TEXT," + // 2: collectAlbumIds
                "\"PAY_ALBUM_IDS\" TEXT);"); // 3: payAlbumIds
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(2, userEmail);
        }
 
        String collectAlbumIds = entity.getCollectAlbumIds();
        if (collectAlbumIds != null) {
            stmt.bindString(3, collectAlbumIds);
        }
 
        String payAlbumIds = entity.getPayAlbumIds();
        if (payAlbumIds != null) {
            stmt.bindString(4, payAlbumIds);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(1, userId);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(2, userEmail);
        }
 
        String collectAlbumIds = entity.getCollectAlbumIds();
        if (collectAlbumIds != null) {
            stmt.bindString(3, collectAlbumIds);
        }
 
        String payAlbumIds = entity.getPayAlbumIds();
        if (payAlbumIds != null) {
            stmt.bindString(4, payAlbumIds);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userEmail
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // collectAlbumIds
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // payAlbumIds
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setUserId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserEmail(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCollectAlbumIds(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPayAlbumIds(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(UserInfo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(UserInfo entity) {
        return null;
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
